In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import os

os.listdir('/content/drive/MyDrive/MutualFundAnalytics')

['Data', 'Reports', 'SQL', 'Dashboard', 'Notebook']

In [3]:
import pandas as pd
import numpy as np
import os
import requests

In [7]:
raw_path = "/content/drive/MyDrive/MutualFundAnalytics/Data/Raw"

In [8]:
os.listdir(raw_path)

['Copy of 06_industry_folio_count.csv',
 'Copy of 08_investor_transactions.csv',
 'Copy of 07_scheme_performance.csv',
 'Copy of 10_benchmark_indices.csv',
 'Copy of 01_fund_master.csv',
 'Copy of 03_aum_by_fund_house.csv',
 'Copy of 02_nav_history.csv',
 'Copy of 05_category_inflows.csv',
 'Copy of 09_portfolio_holdings.csv',
 'Copy of 04_monthly_sip_inflows.csv']

In [9]:
files = [f for f in os.listdir(raw_path) if f.endswith('.csv')]

for file in files:

    print("=" * 60)
    print("Dataset:", file)

    df = pd.read_csv(os.path.join(raw_path, file))

    print("\nShape:")
    print(df.shape)

    print("\nData Types:")
    print(df.dtypes)

    print("\nFirst 5 Rows:")
    print(df.head())

    print("\n")

============================================================
Dataset: Copy of 06_industry_folio_count.csv

Shape:
(21, 6)

Data Types:
month                   object
total_folios_crore     float64
equity_folios_crore    float64
debt_folios_crore      float64
hybrid_folios_crore    float64
others_folios_crore    float64
dtype: object

First 5 Rows:
     month  total_folios_crore  equity_folios_crore  debt_folios_crore  \
0  2022-01               13.26                 9.28               1.86
1  2022-04               13.91                 9.74               1.95
2  2022-07               13.85                 9.69               1.94
3  2022-10               14.12                 9.88               1.98
4  2023-01               14.81                10.37               2.07

   hybrid_folios_crore  others_folios_crore
0                 0.80                 1.33
1                 0.83                 1.39
2                 0.83                 1.38
3                 0.85                 1.41
4                 0.89                 1.48


============================================================
Dataset: Copy of 08_investor_transactions.csv

Shape:
(32778, 13)

Data Types:
investor_id            object
transaction_date       object
amfi_code               int64
transaction_type       object
amount_inr              int64
state                  object
city                   object
city_tier              object
age_group              object
gender                 object
annual_income_lakh    float64
payment_mode           object
kyc_status             object
dtype: object

First 5 Rows:
  investor_id transaction_date  amfi_code transaction_type  amount_inr  \
0   INV003054       2024-01-01     119092              SIP        1834
1   INV002952       2024-01-01     148567       Redemption      392882
2   INV003420       2024-01-01     118636              SIP         912
3   INV003436       2024-01-01     118634              SIP        1102
4   INV004691       2024-01-01     119094          Lumpsum        8682

         state       city city_tier age_group  gender  annual_income_lakh  \
0    Telangana  Hyderabad       T30       56+  Female                77.1
1       Punjab   Amritsar       B30     18-25    Male                 7.1
2      Haryana  Faridabad       B30     36-45    Male                47.2
3  Maharashtra     Mumbai       T30     36-45  Female                54.4
4        Delhi      Noida       T30     26-35    Male                14.5

  payment_mode kyc_status
0          UPI   Verified
1       Cheque   Verified
2      Mandate   Verified
3       Cheque    Pending
4  Net Banking    Pending


============================================================
Dataset: Copy of 07_scheme_performance.csv

Shape:
(40, 19)

Data Types:
amfi_code               int64
scheme_name            object
fund_house             object
category               object
plan                   object
return_1yr_pct        float64
return_3yr_pct        float64
return_5yr_pct        float64
benchmark_3yr_pct     float64
alpha                 float64
beta                  float64
sharpe_ratio          float64
sortino_ratio         float64
std_dev_ann_pct       float64
max_drawdown_pct      float64
aum_crore               int64
expense_ratio_pct     float64
morningstar_rating      int64
risk_grade             object
dtype: object

First 5 Rows:
   amfi_code                                   scheme_name       fund_house  \
0     119551     SBI Bluechip Fund - Regular Plan - Growth  SBI Mutual Fund
1     119552      SBI Bluechip Fund - Direct Plan - Growth  SBI Mutual Fund
2     119598    SBI Small Cap Fund - Regular Plan - Growth  SBI Mutual Fund
3     119599     SBI Small Cap Fund - Direct Plan - Growth  SBI Mutual Fund
4     119120  SBI Magnum Gilt Fund - Regular Plan - Growth  SBI Mutual Fund

    category     plan  return_1yr_pct  return_3yr_pct  return_5yr_pct  \
0  Large Cap  Regular           12.42           12.36           14.45
1  Large Cap   Direct           15.25           11.30           14.23
2  Small Cap  Regular           24.56           23.39           20.67
3  Small Cap   Direct           20.59           23.14           21.82
4       Gilt  Regular            5.34            6.07            5.43

   benchmark_3yr_pct  alpha  beta  sharpe_ratio  sortino_ratio  \
0              11.49   0.87  0.89          0.88           1.29
1               9.52   1.78  0.87          0.81           1.29
2              22.16   1.23  0.89          0.94           1.35
3              22.01   1.13  1.04          0.93           1.67
4               4.47   1.60  0.22          1.52           2.11

   std_dev_ann_pct  max_drawdown_pct  aum_crore  expense_ratio_pct  \
0             14.0            -21.70      14288               1.54
1             14.0            -24.43       1231               0.66
2             25.0            -13.35      19259               1.43
3             25.0            -24.78      36061               0.72
4              4.0             -2.30      24101               0.77

   morningstar_rating risk_grade
0                   4   Moderate
1                   3   Moderate
2                   5  Very High
3                   4  Very High
4                   5        Low


============================================================
Dataset: Copy of 10_benchmark_indices.csv

Shape:
(8050, 3)

Data Types:
date            object
index_name      object
close_value    float64
dtype: object

First 5 Rows:
         date index_name  close_value
0  2022-01-03    NIFTY50     17492.79
1  2022-01-04    NIFTY50     17689.64
2  2022-01-05    NIFTY50     17835.05
3  2022-01-06    NIFTY50     17878.51
4  2022-01-07    NIFTY50     17759.15


============================================================
Dataset: Copy of 01_fund_master.csv

Shape:
(40, 15)

Data Types:
amfi_code               int64
fund_house             object
scheme_name            object
category               object
sub_category           object
plan                   object
launch_date            object
benchmark              object
expense_ratio_pct     float64
exit_load_pct         float64
min_sip_amount          int64
min_lumpsum_amount      int64
fund_manager           object
risk_category          object
sebi_category_code     object
dtype: object

First 5 Rows:
   amfi_code       fund_house                                   scheme_name  \
0     119551  SBI Mutual Fund     SBI Bluechip Fund - Regular Plan - Growth
1     119552  SBI Mutual Fund      SBI Bluechip Fund - Direct Plan - Growth
2     119598  SBI Mutual Fund    SBI Small Cap Fund - Regular Plan - Growth
3     119599  SBI Mutual Fund     SBI Small Cap Fund - Direct Plan - Growth
4     119120  SBI Mutual Fund  SBI Magnum Gilt Fund - Regular Plan - Growth

  category sub_category     plan launch_date                  benchmark  \
0   Equity    Large Cap  Regular  2006-02-14              NIFTY 100 TRI
1   Equity    Large Cap   Direct  2013-01-01              NIFTY 100 TRI
2   Equity    Small Cap  Regular  2009-09-09       BSE 250 SmallCap TRI
3   Equity    Small Cap   Direct  2013-01-01       BSE 250 SmallCap TRI
4     Debt         Gilt  Regular  2000-12-30  CRISIL Dynamic Gilt Index

   expense_ratio_pct  exit_load_pct  min_sip_amount  min_lumpsum_amount  \
0               1.54            1.0             500                1000
1               0.66            1.0             500                1000
2               1.43            1.0             500                1000
3               0.72            1.0             500                1000
4               0.77            0.0             500                1000

    fund_manager risk_category sebi_category_code
0  Sohini Andani      Moderate               EC01
1  Sohini Andani      Moderate               EC01
2  R. Srinivasan     Very High               EC03
3  R. Srinivasan     Very High               EC03
4   Dinesh Ahuja           Low               DC02


============================================================
Dataset: Copy of 03_aum_by_fund_house.csv

Shape:
(90, 5)

Data Types:
date               object
fund_house         object
aum_lakh_crore    float64
aum_crore           int64
num_schemes         int64
dtype: object

First 5 Rows:
         date           fund_house  aum_lakh_crore  aum_crore  num_schemes
0  2022-03-31      SBI Mutual Fund            6.05     605000          186
1  2022-03-31  ICICI Prudential MF            4.65     465000          216
2  2022-03-31     HDFC Mutual Fund            4.35     435000          195
3  2022-03-31      Nippon India MF            2.70     270000          177
4  2022-03-31    Kotak Mahindra MF            2.70     270000          168


============================================================
Dataset: Copy of 02_nav_history.csv

Shape:
(46000, 3)

Data Types:
amfi_code      int64
date          object
nav          float64
dtype: object

First 5 Rows:
   amfi_code        date      nav
0     119551  2022-01-03  54.3856
1     119551  2022-01-04  54.3474
2     119551  2022-01-05  54.6869
3     119551  2022-01-06  55.4550
4     119551  2022-01-07  55.3692


============================================================
Dataset: Copy of 05_category_inflows.csv

Shape:
(144, 3)

Data Types:
month                object
category             object
net_inflow_crore    float64
dtype: object

First 5 Rows:
     month         category  net_inflow_crore
0  2024-04        Large Cap            2413.0
1  2024-04          Mid Cap            3897.0
2  2024-04        Small Cap            3533.0
3  2024-04        Flexi Cap            4947.0
4  2024-04  Large & Mid Cap            4214.0


============================================================
Dataset: Copy of 09_portfolio_holdings.csv

Shape:
(322, 8)

Data Types:
amfi_code              int64
stock_symbol          object
stock_name            object
sector                object
weight_pct           float64
market_value_cr      float64
current_price_inr    float64
portfolio_date        object
dtype: object

First 5 Rows:
   amfi_code stock_symbol                stock_name       sector  weight_pct  \
0     119551    POWERGRID    Power Grid Corporation    Utilities       13.85
1     119551     HDFCBANK             HDFC Bank Ltd      Banking       11.19
2     119551       GRASIM     Grasim Industries Ltd  Diversified        9.90
3     119551      DRREDDY  Dr. Reddy's Laboratories       Pharma        4.76
4     119551   ASIANPAINT          Asian Paints Ltd       Paints       10.25

   market_value_cr  current_price_inr portfolio_date
0           737.09            6011.08     2025-12-31
1            88.97            1074.65     2025-12-31
2           208.45            5964.59     2025-12-31
3           161.32            3748.82     2025-12-31
4           725.90            1321.45     2025-12-31


============================================================
Dataset: Copy of 04_monthly_sip_inflows.csv

Shape:
(48, 6)

Data Types:
month                         object
sip_inflow_crore               int64
active_sip_accounts_crore    float64
new_sip_accounts_lakh        float64
sip_aum_lakh_crore           float64
yoy_growth_pct               float64
dtype: object

First 5 Rows:
     month  sip_inflow_crore  active_sip_accounts_crore  \
0  2022-01             11517                       4.91
1  2022-02             11438                       4.93
2  2022-03             12328                       5.09
3  2022-04             11863                       5.48
4  2022-05             12286                       5.55

   new_sip_accounts_lakh  sip_aum_lakh_crore  yoy_growth_pct
0                   9.10                4.80             NaN
1                   8.20                4.85             NaN
2                  10.50                5.01             NaN
3                   9.52                5.12             NaN
4                   8.10                5.15             NaN

In [10]:
import requests
import pandas as pd

url = "https://api.mfapi.in/mf/125497"

response = requests.get(url)

print("Status Code:", response.status_code)

data = response.json()

print(data.keys())

Status Code: 200
dict_keys(['meta', 'data', 'status'])

In [11]:
data['data'][:5]

[{'date': '01-06-2026', 'nav': '192.31950'},
 {'date': '31-05-2026', 'nav': '193.68360'},
 {'date': '29-05-2026', 'nav': '193.68480'},
 {'date': '27-05-2026', 'nav': '195.05010'},
 {'date': '26-05-2026', 'nav': '194.22580'}]

In [12]:
nav_df = pd.DataFrame(data['data'])

nav_df.head()

         date        nav
0  01-06-2026  192.31950
1  31-05-2026  193.68360
2  29-05-2026  193.68480
3  27-05-2026  195.05010
4  26-05-2026  194.22580

In [13]:
save_path = "/content/drive/MyDrive/MutualFundAnalytics/Data/Raw/HDFC_TOP100_NAV.csv"

nav_df.to_csv(save_path, index=False)

print("File Saved Successfully")

File Saved Successfully

In [14]:
schemes = {
    "SBI_Bluechip": 119551,
    "ICICI_Bluechip": 120503,
    "Nippon_LargeCap": 118632,
    "Axis_Bluechip": 119092,
    "Kotak_Bluechip": 120841
}

In [16]:
for name, code in schemes.items():

    url = f"https://api.mfapi.in/mf/{code}"

    response = requests.get(url)

    data = response.json()

    df = pd.DataFrame(data['data'])

    save_file = f"/content/drive/MyDrive/MutualFundAnalytics/Data/Raw/{name}.csv"

    df.to_csv(save_file, index=False)

    print(f"{name} saved successfully")

SBI_Bluechip saved successfully
ICICI_Bluechip saved successfully
Nippon_LargeCap saved successfully
Axis_Bluechip saved successfully
Kotak_Bluechip saved successfully

In [17]:
import pandas as pd

fund_master = pd.read_csv(
    f"{raw_path}/Copy of 01_fund_master.csv"
)

fund_master.head()

,amfi_code,fund_house,scheme_name,category,sub_category,plan,launch_date,benchmark,expense_ratio_pct,exit_load_pct,min_sip_amount,min_lumpsum_amount,fund_manager,risk_category,sebi_category_code
0,119551,SBI Mutual Fund,SBI Bluechip Fund - Regular Plan - Growth,Equity,Large Cap,Regular,2006-02-14,NIFTY 100 TRI,1.54,1.0,500,1000,Sohini Andani,Moderate,EC01
1,119552,SBI Mutual Fund,SBI Bluechip Fund - Direct Plan - Growth,Equity,Large Cap,Direct,2013-01-01,NIFTY 100 TRI,0.66,1.0,500,1000,Sohini Andani,Moderate,EC01
2,119598,SBI Mutual Fund,SBI Small Cap Fund - Regular Plan - Growth,Equity,Small Cap,Regular,2009-09-09,BSE 250 SmallCap TRI,1.43,1.0,500,1000,R. Srinivasan,Very High,EC03
3,119599,SBI Mutual Fund,SBI Small Cap Fund - Direct Plan - Growth,Equity,Small Cap,Direct,2013-01-01,BSE 250 SmallCap TRI,0.72,1.0,500,1000,R. Srinivasan,Very High,EC03
4,119120,SBI Mutual Fund,SBI Magnum Gilt Fund - Regular Plan - Growth,Debt,Gilt,Regular,2000-12-30,CRISIL Dynamic Gilt Index,0.77,0.0,500,1000,Dinesh Ahuja,Low,DC02

In [19]:
fund_master.columns

Index(['amfi_code', 'fund_house', 'scheme_name', 'category', 'sub_category',
       'plan', 'launch_date', 'benchmark', 'expense_ratio_pct',
       'exit_load_pct', 'min_sip_amount', 'min_lumpsum_amount', 'fund_manager',
       'risk_category', 'sebi_category_code'],
      dtype='object')

In [20]:
print(fund_master['fund_house'].unique())

['SBI Mutual Fund' 'HDFC Mutual Fund' 'ICICI Prudential MF'
 'Nippon India MF' 'Kotak Mahindra MF' 'Axis Mutual Fund'
 'Aditya Birla Sun Life MF' 'UTI Mutual Fund' 'Mirae Asset MF'
 'DSP Mutual Fund']

In [26]:
print("Number of Fund Houses:")
print(fund_master['fund_house'].nunique())

Number of Fund Houses:
10

In [22]:
print(
fund_master['category'].unique()
)

['Equity' 'Debt']

In [23]:
print(
fund_master['sub_category'].unique()
)

['Large Cap' 'Small Cap' 'Gilt' 'Mid Cap' 'Short Duration' 'Value'
 'Liquid' 'Index/ETF' 'Flexi Cap' 'Index' 'Large & Mid Cap' 'ELSS']

In [27]:
print(fund_master['risk_category'].unique())

['Moderate' 'Very High' 'Low' 'High' 'Moderately High']

In [28]:
print(
fund_master['risk_category'].value_counts()
)

risk_category
Moderate           16
High                8
Very High           6
Low                 6
Moderately High     4
Name: count, dtype: int64

In [29]:
report = f"""
FUND MASTER SUMMARY

Total Funds:
{len(fund_master)}

Unique Fund Houses:
{fund_master['fund_house'].nunique()}

Unique Categories:
{fund_master['category'].nunique()}

Unique Sub Categories:
{fund_master['sub_category'].nunique()}

Unique Risk Categories:
{fund_master['risk_category'].nunique()}
"""

print(report)

FUND MASTER SUMMARY

Total Funds:
40

Unique Fund Houses:
10

Unique Categories:
2

Unique Sub Categories:
12

Unique Risk Categories:
5

In [30]:
with open(
"/content/drive/MyDrive/MutualFundAnalytics/Reports/fund_master_summary.txt",
"w"
) as file:

    file.write(report)

print("Summary Saved")

Summary Saved

In [31]:
nav_history = pd.read_csv(
    f"{raw_path}/Copy of 02_nav_history.csv"
)

nav_history.head()

   amfi_code        date      nav
0     119551  2022-01-03  54.3856
1     119551  2022-01-04  54.3474
2     119551  2022-01-05  54.6869
3     119551  2022-01-06  55.4550
4     119551  2022-01-07  55.3692

In [32]:
nav_history.columns.tolist()

['amfi_code', 'date', 'nav']

In [33]:
missing_codes = set(
    fund_master['amfi_code']
) - set(
    nav_history['amfi_code']
)

print("Missing Codes:", len(missing_codes))

Missing Codes: 0

In [35]:
for col in fund_master.columns:
    print(col, ":", fund_master[col].isnull().sum())

amfi_code : 0
fund_house : 0
scheme_name : 0
category : 0
sub_category : 0
plan : 0
launch_date : 0
benchmark : 0
expense_ratio_pct : 0
exit_load_pct : 0
min_sip_amount : 0
min_lumpsum_amount : 0
fund_manager : 0
risk_category : 0
sebi_category_code : 0

In [36]:
print(
    "Duplicate Rows:",
    fund_master.duplicated().sum()
)

Duplicate Rows: 0

In [37]:
quality_report = f"""
DATA QUALITY REPORT

Fund Master Records:
{len(fund_master)}

NAV History Records:
{len(nav_history)}

Duplicate Records:
{fund_master.duplicated().sum()}

Missing AMFI Codes:
{len(missing_codes)}
"""

print(quality_report)

DATA QUALITY REPORT

Fund Master Records:
40

NAV History Records:
46000

Duplicate Records:
0

Missing AMFI Codes:
0

In [38]:
with open(
"/content/drive/MyDrive/MutualFundAnalytics/Reports/data_quality_report.txt",
"w"
) as f:

    f.write(quality_report)

print("Data Quality Report Saved")

Data Quality Report Saved

In [40]:
print(fund_master.shape)
print(nav_history.shape)

(40, 15)
(46000, 3)